# Generated by Django 3.1.3 on 2020-11-10 17:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0004_cart'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Package Accepted.', 'accepted'), ('Packed', 'packed'), ('Shipping', 'shipping'), ('Shipped', 'shipped')], max_length=20)),
                ('cart', models.ManyToManyField(to='store.Product')),
                ('payer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payer', to=settings.AUTH_USER_MODEL)),
                ('shipper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipper', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
