# Generated by Django 3.1.3 on 2020-11-10 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_auto_20201110_1735'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Accepted', 'accepted'), ('Packed', 'packed'), ('Shipping', 'shipping'), ('Shipped', 'shipped')], max_length=20),
        ),
    ]
